CREATE TABLE "role" (
  "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp,
  "created_by" varchar(255),
  "updated_by" varchar(255)
);

CREATE TABLE "permissions" (
  "permission_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp,
  "created_by" varchar(255),
  "updated_by" varchar(255)
);

CREATE TABLE "merchant" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(255),
  "is_active" bool,
  "password" varchar(255),
  "merchant_level" varchar(255),
  "email" varchar(255),
  "created_at" timestamp,
  "updated_at" timestamp,
  "created_by" varchar(255),
  "updated_by" varchar(255),
  "subscription_type_id" int
);

CREATE TABLE "subscription_type" (
  "subscription_type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "description" text,
  "price" numeric(10, 2),
  "created_at" timestamp,
  "updated_at" timestamp,
  "created_by" varchar(255),
  "updated_by" varchar(255)
);

CREATE TABLE "user_role" (
  "user_role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "role_id" int,
  "created_at" timestamp,
  "updated_at" timestamp,
  "created_by" varchar(255),
  "updated_by" varchar(255)
);

CREATE TABLE "role_permissions" (
  "role_id" int,
  "permission_id" int,
  "created_at" timestamp,
  "updated_at" timestamp,
  "created_by" varchar(255),
  "updated_by" varchar(255)
);

CREATE TABLE "kyb" (
  "kyb_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "business_name" varchar(255),
  "registration_number" varchar(255),
  "address" varchar(255),
  "website" varchar(255),
  "region" varchar(255),
  "phone_number" varchar(15),
  "created_at" timestamp,
  "updated_at" timestamp,
  "created_by" varchar(255),
  "updated_by" varchar(255)
);

CREATE TABLE "transaction_data" (
  "transaction_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "transaction_type" varchar(255),
  "psp_id" int,
  "trace_id" varchar(255),
  "payment_method" varchar(255),
  "amount" numeric(10, 2),
  "currency" varchar(3),
  "payment_processor" varchar(255),
  "card_token" varchar(255),
  "timestamp" timestamp,
  "psp_transaction_id" varchar(255),
  "card_type" varchar(50),
  "attempts_amount" int,
  "transaction_status" varchar(255),
  "order_id" varchar(255),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "global_psp_configuration" (
  "psp_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "merchant_id" int,
  "psp_name" varchar(255),
  "cards" bool,
  "card_type" varchar(50),
  "region" varchar(255),
  "alternative_payment_method" varchar(255),
  "crypto" bool,
  "base_currency" varchar(3),
  "settle" varchar(255),
  "emt_currency" varchar(3),
  "minimum_volume" numeric(10, 2),
  "maximum_value" numeric(10, 2),
  "risk_appetite" varchar(255),
  "created_at" timestamp,
  "updated_at" timestamp,
  "created_by" varchar(255),
  "updated_by" varchar(255)
);

CREATE TABLE "merchant_psp_configuration" (
  "configuration_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "merchant_id" int,
  "enabled_psp_id" int,
  "supported_currencies" varchar(255),
  "minimum_value" numeric(10, 2),
  "max_volume" numeric(10, 2),
  "settlement_currency" varchar(3),
  "region" varchar(255),
  "is_active" bool,
  "created_at" timestamp,
  "updated_at" timestamp,
  "created_by" varchar(255),
  "updated_by" varchar(255)
);

CREATE TABLE "merchant_widget_configuration" (
  "widget_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "merchant_id" int,
  "psp_configuration_id" int,
  "configuration" json,
  "created_at" timestamp,
  "updated_at" timestamp,
  "created_by" varchar(255),
  "updated_by" varchar(255)
);

CREATE TABLE "routing_configuration" (
  "routing_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "merchant_id" int,
  "route_id" varchar(255),
  "payment_country" varchar(255),
  "bin_country" varchar(255),
  "card_type" varchar(50),
  "currency" varchar(3),
  "minimum_amount" numeric(10, 2),
  "max_amount" numeric(10, 2),
  "device" varchar(255),
  "psp_id" int,
  "configuration_id" int,
  "created_at" timestamp,
  "updated_at" timestamp,
  "created_by" varchar(255),
  "updated_by" varchar(255)
);

ALTER TABLE "merchant" ADD FOREIGN KEY ("subscription_type_id") REFERENCES "subscription_type" ("subscription_type_id");

ALTER TABLE "user_role" ADD FOREIGN KEY ("user_id") REFERENCES "merchant" ("user_id");

ALTER TABLE "user_role" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("role_id");

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("role_id");

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("permission_id") REFERENCES "permissions" ("permission_id");

ALTER TABLE "kyb" ADD FOREIGN KEY ("user_id") REFERENCES "merchant" ("user_id");

ALTER TABLE "transaction_data" ADD FOREIGN KEY ("user_id") REFERENCES "merchant" ("user_id");

ALTER TABLE "transaction_data" ADD FOREIGN KEY ("psp_id") REFERENCES "global_psp_configuration" ("psp_id");

ALTER TABLE "global_psp_configuration" ADD FOREIGN KEY ("merchant_id") REFERENCES "merchant" ("user_id");

ALTER TABLE "merchant_psp_configuration" ADD FOREIGN KEY ("merchant_id") REFERENCES "merchant" ("user_id");

ALTER TABLE "merchant_psp_configuration" ADD FOREIGN KEY ("enabled_psp_id") REFERENCES "global_psp_configuration" ("psp_id");

ALTER TABLE "merchant_widget_configuration" ADD FOREIGN KEY ("merchant_id") REFERENCES "merchant" ("user_id");

ALTER TABLE "merchant_widget_configuration" ADD FOREIGN KEY ("psp_configuration_id") REFERENCES "merchant_psp_configuration" ("configuration_id");

ALTER TABLE "routing_configuration" ADD FOREIGN KEY ("merchant_id") REFERENCES "merchant" ("user_id");

ALTER TABLE "routing_configuration" ADD FOREIGN KEY ("psp_id") REFERENCES "global_psp_configuration" ("psp_id");

ALTER TABLE "routing_configuration" ADD FOREIGN KEY ("configuration_id") REFERENCES "merchant_psp_configuration" ("configuration_id");
